### ISSUE TITLE
Timing out on failed request is non-compliant

### ISSUE THREAD

**Issue by gdm85** [m13253/dns-over-https#10]
I have found that the changes in c4b2236cf9ac6cdf9e8e08991efc407b225a77b3 make the DNS server (running locally as a client) non-compliant. See also: https://github.com/golang/go/issues/25321

**Comment by gdm85** [comment]
Nevermind. The lookup timeout is not due to that commit, sorry for the noise.

**Comment by m13253** [comment]
Thank you for your contribution to this project! 🎉

The suppression of reply packet happens only when upstream servers time out.
For any other errors, a packet with either SERVFAIL or NXDOMAIN will be replied.

This suppression is a fix for mDNSResponder (the DNS cache on macOS and iOS).
It caches SERVFAIL responses without retrying it, breaking the network for several minutes.
The caching behavior is totally [standard-compliant](https://tools.ietf.org/html/rfc2308#section-7.1), I have nothing to complain with it.
My solution is to deliberately produce a timeout so it matches the same behavior as a real timeout.

**Comment by gdm85** [comment]
@m13253 I had already said "nevermind", but thanks for the explanation
