### ISSUE TITLE
New minimum Go version

### ISSUE THREAD

**Issue by mcmufffin** [m13253/dns-over-https#102]
Hello,

just wanted to point out that for 2.2.5 you need atleast go 1.13 for ed25519 crypto to work, so it wont compile on debian 10.

May you please update the readme? 

> From Source
> 
>     Install Go, at least version 1.10.

Thanks

**Comment by m13253** [comment]
Solved via 2e36b4ebcdb8a1a102ea86370d7f8b1f1e72380a.
