### ISSUE TITLE
Question: Way to include dns OPT values in response?

### ISSUE THREAD

**Issue by davehouser1** [m13253/dns-over-https#106]
Appendix A of RFC8484 includes the following:
"The protocol must ensure interoperability by specifying a single format for requests and responses that is mandatory to implement. That format must be able to support future modifications to the DNS protocol including the inclusion of one or more EDNS options (including those not yet defined)."

I am looking for HTTP responses to include OPT values referenced in [RFC7871 ](https://datatracker.ietf.org/doc/html/rfc7871) section 6, such as CSUBNET to include the original requester layer3 address. 

Is there a way to enable this in dns-over-https settings?

**Comment by m13253** [comment]
If you are using the RFC8484 binary format, directly encode your OPT values.
If you are using the Google JSON format, use `edns_client_subnet=xxx.xxx.xxx.0/24`.
