### ISSUE TITLE
toml: cannot load TOML value of type string into a Go slice

### ISSUE THREAD

**Issue by efolch** [m13253/dns-over-https#11]
Config file seems to fail to load with the error message on the title. Aparently it's related to data format.

In the .conf file I changed:
`listen = "127.1.2.3:123" `
to 
`listen = ["127.1.2.3:123"]`

Not sure if that's correct, but apparetnly that got rid of the error message and doh-client started to work.
Go version is 1.10.1 linux/arm.

**Comment by efolch** [comment]
Damn it! :) I should have payed attention to the changelog or the .conf file in the src directory. 
I checked `/etc/doh-client.conf` (in my case that file is unmodified as I copied and renamed the conf files I use), but that wasn't replaced after `make install`. 
Maybe it would be a good idea to install and overwrite an `/etc/doh-client.conf.example` or something like this?

Thanks

**Comment by m13253** [comment]
> Maybe it would be a good idea to install and overwrite an /etc/doh-client.conf.example or something like this?

Thank you for your suggestion. I will implement this when I am free.

**Comment by m13253** [comment]
Fixed in 71b8c093c0d13f36b3bbf6cf0c58af3027cd1b1c. Closing.
