### ISSUE TITLE
Go import `invalid version: module contains a go.mod file, so major version must be compatible: should be v0 or v1, not v2`

### ISSUE THREAD

**Issue by leiless** [m13253/dns-over-https#115]
I want to upgrade the dependency of `m13253/dns-over-https` to `v2.2.5` of my go package, however, I got:

```
$ docker run -it --rm golang:1.16-buster
root@426057fa6ca9:/go# go get -v github.com/m13253/dns-over-https@v2.2.5
go get: github.com/m13253/dns-over-https@v2.2.5: invalid version: module contains a go.mod file, so major version must be compatible: should be v0 or v1, not v2

```

It's mainly because the current Go package module isn't compliant with the Go module hierarchy.

An obvious solution would be:

* Change import path of `github.com/m13253/dns-over-https` to `github.com/m13253/dns-over-https/v2`
Need to change `go.mod` module path
Examples:
https://github.com/casbin/casbin
https://github.com/cespare/xxhash
https://github.com/google/martian
https://github.com/nats-io/nats-server

### SEE ALSO

https://golang.cafe/blog/how-to-upgrade-to-a-major-version-in-go.html
https://archive.is/VohDN

**Comment by m13253** [comment]
Oh... This is a breaking change.

This software was created way before Go's new module system.
I don't understand why this happen, since Go always maintained backwards compatibility in the past, until this change.

I would be very happy to receive a PR, if you have time to fix this issue.

**Comment by leiless** [comment]
I believe that Go updated its module system(for semver) since 1.9.7+, 1.10.3+, and 1.11

https://github.com/golang/go/wiki/Modules#semantic-import-versioning
https://github.com/golang/go/wiki/Modules#releasing-modules-v2-or-higher
https://github.com/golang/go/wiki/Modules#how-are-v2-modules-treated-in-a-build-if-modules-support-is-not-enabled-how-does-minimal-module-compatibility-work-in-197-1103-and-111

> I would be very happy to receive a PR, if you have time to fix this issue.

I'll do it ASAP if I'm available.

**Comment by m13253** [comment]
Thank you so much for helping me solve the issue!

I haven't been following the recent updates from Go official team for quite a long time. I'm so glad that you helped me!

**Comment by leiless** [comment]
You're welcome 😆, you may consider releasing a new tag(when the next release tag is stabilized), so I can refer to it(otherwise I can only use the latest `HEAD` commit).

**Comment by m13253** [comment]
> you may consider releasing a new tag

Done!
