### ISSUE TITLE
Websocket support

### ISSUE THREAD

**Issue by brotaxt** [m13253/dns-over-https#121]
Hey,
Iam using nginx as a reverse proxy for doh-server. 
The last few days Ive read many guides and some of them suggest to activate websocket in nginx with your doh-server.

`proxy_set_header Upgrade $http_upgrade;`

But, does the doh-server component support websocket connections at all? 

Ive tried to connect with websocat_linux64 to the doh-server to figure it out, but that doesn't seem to work.

Greetings!

**Comment by m13253** [comment]
DoH is a very simple protocol. There is no Websocket in it.
Therefore, you don't need to enable Websocket support in Nginx.
(But you can do it if you need it for other services to run.)

**Comment by brotaxt** [comment]
Alright, thank your very much! :-)
