### ISSUE TITLE
json-dns: Record data contains newline

### ISSUE THREAD

**Issue by brotaxt** [m13253/dns-over-https#122]
When using `[[upstream.upstream_google]]` and activating EDNS Client Subnet in dnsmasq. I get tons of _Record data contains newline_ messages from doh-client.

```
doh-client[4535]: 2022/02/02 09:08:10 json-dns: Record data contains newline: "\n;; OPT PSEUDOSECTION:\n; EDNS: version 0; flags: ; udp: 1232"
doh-client[4535]: 2022/02/02 09:08:10 json-dns: Record data contains newline: "\n;; OPT PSEUDOSECTION:\n; EDNS: version 0; flags: ; udp: 1232"
doh-client[4535]: 2022/02/02 09:08:10 json-dns: Record data contains newline: "\n;; OPT PSEUDOSECTION:\n; EDNS: version 0; flags: ; udp: 1232"
doh-client[4535]: 2022/02/02 09:08:20 json-dns: Record data contains newline: "\n;; OPT PSEUDOSECTION:\n; EDNS: version 0; flags: ; udp: 1232"
doh-client[4535]: 2022/02/02 09:08:20 json-dns: Record data contains newline: "\n;; OPT PSEUDOSECTION:\n; EDNS: version 0; flags: ; udp: 1232"
doh-client[4535]: 2022/02/02 09:08:27 json-dns: Record data contains newline: "\n;; OPT PSEUDOSECTION:\n; EDNS: version 0; flags: ; udp: 1232"
doh-client[4535]: 2022/02/02 09:08:32 json-dns: Record data contains newline: "\n;; OPT PSEUDOSECTION:\n; EDNS: version 0; flags: ; udp: 1232"
```

After changing the upstream to `[[upstream.upstream_ietf]]` the messages doesn't appear anymore.

Is this an expected behaviour?

Greetings!

**Comment by brotaxt** [comment]
i'm experiencing some really weird issues with youtube.de / youtube.com when using `[[upstream.upstream_ietf]] `

One Device in my network cannot access youtube, when using IETF. The Website shows "you are offline" and after refreshing the Website I get "nxdomain". However nslookup on youtube.com and youtube.de works fine. The dnsmasq-logs doesn't show anything obvious. All queried domains are getting resolved.

When I change the doh-client config to` [[upstream.upstream_google]] ` youtube works as expected. 

Iam using a local dnsmasq, which forwards my dns requests to another dnsmasq on a VPS which in turn uses the doh-client to resolve the dns queries.

**Comment by m13253** [comment]
IETF and Google are totally two different protocols.
If dnsmasq only supports one protocol, you should only use that protocol.

Furthermore, uploading your configuration file and detailed log (enable `verbose`) would be helpful in diagnosing the problem.

**Comment by brotaxt** [comment]
dnsmasq only forwards the requests to the doh-client.  Iam surprised about two things.

- Why youtube.com works with Google and not with IETF, other Websites works as expected.
-  The mentioned error message "Record data contains newline: "\n" when using Google as upstream doh-protocol.

doh-client.conf

```
listen = [
    "127.0.0.1:5380",
    "[::1]:5380",

]

[upstream]

upstream_selector = "random"

[[upstream.upstream_google]]
    url = "https://dns.nextdns.io/a6dacc"
    weight = 100


[others]
bootstrap = [

    "8.8.8.8:53",
    "8.8.4.4:53",

]

passthrough = [
]

timeout = 30
no_cookies = true
no_ecs = false
no_ipv6 = false
no_user_agent = false
verbose = false
insecure_tls_skip_verify = false
```


/etc/dnsmasq.conf
```
localise-queries
no-resolv


cache-size=10000

server=127.0.0.1#5380
server=::1#5380

log-async
domain-needed
expand-hosts
bogus-priv
interface=eth0
```

**Comment by m13253** [comment]
I can reproduce your results. Here is my conclusion:

1. NextDNS supports both IETF and Google mode. Both mode should work.
2. The “Record data contains newline” message is actually a warning. It will drop the affected record, which will not affect the DNS resolution.
3. While trying to resolve YouTube's IP address with ECS on, NextDNS waited for a couple of seconds before returning the results.

Therefore, I would suggest you to increase the timeout duration and/or retry interval in dnsmasq (both home and VPS side). Sometimes dnsmasq is not patient enough to wait for the result to come in.

You can also use the command `dig` to diagnose DNS problems:
```
$ dig -p5380 @127.0.0.1 www.youtube.com +dnssec +subnet=1.1.1.0/24
```
