### ISSUE TITLE
Missing git tag for 2.3.1 release

### ISSUE THREAD

**Issue by felixonmars** [m13253/dns-over-https#125]
Hi, please make a git tag for 2.3.1 release if it's indeed stable now. Thanks!

**Comment by m13253** [comment]
Thank you for reporting.
There is no update between 2.3.0 and 2.3.1 (for quite a while).

**Comment by felixonmars** [comment]
Ah, you are right. I'll blame the one flagging the Arch Linux package as out-of-date then.

Sorry for the noise :P
