### ISSUE TITLE
authoratative dns home server port 53 filterred by vodafone spain bypass

### ISSUE THREAD

**Issue by bgman111111** [m13253/dns-over-https#126]
Hi

I want to know how to make my dns to be server so when someone surf my website can find it. I dont want to use goddady domain webgui i want to use my BIND server. POrt 53 that has to work is FILTERED, i have it open and youget signal comment it is blocked. I PAY money for freedom not for closed. So is there way make it work. I want to have my proper website and dont DEPENd of govenemntal ILEGALY SPY im human AND WE WANT FREEDOM. Do you read me fucking governments WE ARE NOT EXPERIMENTS Please someone help me. i have idea. if port 53 is blocked, this doh to work on different open port and dns server to work on port 53, so when someone surf domain.com to point to my ip 2.2.2.2 this is example. port 53 is blocked so it will advice doh servr that my ip has dns server and send all consults to my open port, like 666, becouse vodafone spain too has blocked port 54. Fuckin shit what has happend with port 54, it is innormal to clse port 53 and now port 54. Why you dont kick your head in the mothers asses. Normal computer dont know that port 53 is blocked, so they go to doh server and doh say, hey he has port dns x open, send there his consults. And ivan go there. http://domain.com -> x.x.x.x -> 666 -> doh --> 53 doh -->53 --> x.x.x.x -> 666 -> domain.com

Please Include i read that pihole, i use too opnsense, please do something.

**Comment by m13253** [comment]
Sorry I cannot understand your request.
Currently DoH cannot act as an authoritative server.
If you want to run a DNS server, I would recommend you rent a VPS to run your DNS server.

**Comment by bgman111111** [comment]
thank you man. is there way make it work.
