### ISSUE TITLE
Purpose of the NetworkManager dispatcher scripts

### ISSUE THREAD

**Issue by soystemd** [m13253/dns-over-https#127]
Hi,
What is the purpose of the [NetworkManager dispatcher scripts](https://github.com/m13253/dns-over-https/tree/b3ddec1/NetworkManager/dispatcher.d)?
I couldn't find any info on why doh needs to be restarted every time an interface goes up or down.

**Comment by m13253** [comment]
This dispatcher scripts simply restarts the DoH client or server when there is a network change.
This prevents various bugs related to connection pooling.

If you don't use NetworkManager, you can write similar scripts to achieve the same purpose.
If you don't observe this kind of issue, you can safely ignore these scripts.

**Comment by soystemd** [comment]
I see, thanks for clearing it up.
