### ISSUE TITLE
(DoQ) consider add quick HTTP/3 support ?

### ISSUE THREAD

**Issue by GreyXor** [m13253/dns-over-https#129]
What do you think about https://datatracker.ietf.org/doc/rfc9250/ support ?

QUIC features that are very useful for reducing latency at connection establishment, such as 0-RTT, have privacy implications by allowing the same user (or more precisely, the same machine) to be tracked. And this works even if the machine has changed its IP address in the meantime.

**Comment by m13253** [comment]
However, DoQ is weak when considering the ability to circumvent nationwide Internet censorship.
QUIC communication is heavily interfered in countries where the users need encrypted DNS the most.

If Go supports automatic QUIC upgrading, maybe supporting DoQ could be as easy as one line of code.

**Comment by GreyXor** [comment]
Yes that's why I actually closed the ticket. Thanks @m13253
