### ISSUE TITLE
 IP guessing feature ignores any private IP

### ISSUE THREAD

**Issue by meluvalli** [m13253/dns-over-https#130]
Is there anyway to override this?  Also, side note, where are logs located? I have verbose = true, but where do I see the logs?

**Comment by m13253** [comment]
Go modify json-dns/globalip.go.

There is no option on this, because I don't think there is a need to toggle this. For those users like you who knows what they are doing, they also know how to modify the code so …

**Comment by gdm85** [comment]
> Also, side note, where are logs located? I have verbose = true, but where do I see the logs?

Logs are sent to stderr, you most likely can access them with `journalctl` on your system. Perhaps we can add a hint about this in README.md

I am closing this because there is no intention to add a toggle and no reply for a couple months already.

Thanks!
