### ISSUE TITLE
[Proposal] Removing the workaround for Firefox 61-62

### ISSUE THREAD

**Issue by Gontier-Julien** [m13253/dns-over-https#136]
As the title say, i propose to remove the workaround for Firefox 61-62, as those versions shouldn't be used by anyone anyway.

So let me know what you're thought on this, i can add a pull request to remove the workaround. ^^

**Comment by m13253** [comment]
Let's remove it now.
And I plan to release a new minor version after removing this.
Because it's been a while since last release.

**Comment by Gontier-Julien** [comment]
> Let's remove it now. And I plan to release a new minor version after removing this. Because it's been a while since last release.

Alright i'll do a commit today ^^
