### ISSUE TITLE
Systemd user nobody

### ISSUE THREAD

**Issue by omgold** [m13253/dns-over-https#139]
The systemd units set the user to nobody. As this not advisable for security reasons, system produces annoying warnings

`Okt 06 09:58:58 systemd[1]: [🡕] /usr/lib/systemd/system/doh-client.service:15: Special user nobody configured, this is not safe!`

My suggestion would be to user `DynamicUser=yes` instead of `User=nobody`

**Comment by m13253** [comment]
I support this change.
Have you checked whether the change introduces new bugs? (Especially permission related ones.)

**Comment by omgold** [comment]
Well, it works for me, and journal doesn't produce any messages. So I guess it is okay.

**Comment by m13253** [comment]
I'm going to merge PR #140 in 2–3 days.
Anyone who is actively using dns-over-https with systemd can help me test this change.

**Comment by vinnyperella** [comment]
I just added it to my instance and it seems to be fine so far.
