### ISSUE TITLE
It does not compile and gives an error

### ISSUE THREAD

**Issue by mb-real** [m13253/dns-over-https#147]
mb@mb-m52ls3p /m/m/G/C/d/dns-over-https (master)> sudo make install

**[ -e doh-client/doh-client ] || make doh-client/doh-client**

make[1]: Entering directory '/media/mb/GLOBAL/Clone/dns-over-https/dns-over-https'
cd doh-client && go build

**build github.com/m13253/dns-over-https/v2/doh-client: cannot load io/fs: malformed module path "io/fs": missing dot in first path element**

**make[1]: *** [Makefile:57: doh-client/doh-client] Error 1**
**make[1]: Leaving directory '/media/mb/GLOBAL/Clone/dns-over-https/dns-over-https'**
**make: *** [Makefile:29: install] Error 2**

mb@mb-m52ls3p /m/m/G/C/d/dns-over-https (master) [2]> go version
**_go version go1.13.8 linux/amd64_**

**Comment by Jamesits** [comment]
This project [requires Go 1.20+](https://github.com/m13253/dns-over-https/blob/master/go.mod#L3), and Go 1.13 [has been out of support for a long time](https://go.dev/doc/devel/release#policy). Would it be possible for you to upgrade to Go 1.20, or could we know if you have any specific needs that require Go 1.13?
