### ISSUE TITLE
Feature Request: Rate Limiting

### ISSUE THREAD

**Issue by ztheory** [m13253/dns-over-https#149]
It'd be nice to have built-in rate limiting. Specifically, requests per second from a specific source IP.

**Comment by m13253** [comment]
I’m a little bit confused because should we do it on Nginx side?

**Comment by ztheory** [comment]
Server is set to listen on the port directly with no proxy in front of it.

**Comment by m13253** [comment]
I recommend a reverse proxy to perform OCSP stapling.
Please refer to the documentations for configuration guidelines.
