### ISSUE TITLE
Does dns-over-https have cache?

### ISSUE THREAD

**Issue by Sherlock-Holo** [m13253/dns-over-https#2]
On my server, I use `dnsmasq` to cache to DNS resolve result, I want to use doh directly, I searched `cache` in this repo and it seems there are not codes about cache the result.

So I wonder if `dns-over-https` has the feature about cache the result.

**Comment by m13253** [comment]
DNS-over-HTTPS does not cache results. However it emits HTTP cache headers so you can use either HTTP cache or DNS cache.
I recommend using DOH with Unbound or Knot-resolver. Either of them does cache and validates DNSSEC records.

**Comment by Sherlock-Holo** [comment]
Thanks for your reply, I think I will try `Unbound` or `Knot-resolver`.

**Comment by m13253** [comment]
Just to remind you that your system might already have a cache.
On Linux, it is usually called `nscd` and is integrated in `glibc`.
Use `nscd -g` to check if it is enabled on your system.

**Comment by Sherlock-Holo** [comment]
网域名称缓存精灵...
What the hell...?
Why my Arch Linux has this strange program? 😂

Star Brilliant <notifications@github.com>于2017年12月21日周四 下午10:08写道：

**Comment by Sherlock-Holo** [comment]
oh... it's a part of glibc…

Sherlock Holo <sherlockya@gmail.com> 于 2017年12月22日周五 14:59写道：
