### ISSUE TITLE
golang 1.10 required?

### ISSUE THREAD

**Issue by mikedoug** [m13253/dns-over-https#27]
The documentation states that you need golang 1.9 as a minimum, but attempting to build fails with:

```
/home/you/gopath/src/github.com/miekg/dns/msg_helpers.go:271:8: undefined: strings.Builder
/home/you/gopath/src/github.com/miekg/dns/serve_mux.go:43:9: undefined: strings.Builder
```

A quick google shows that strings.Builder was added in golang 1.10.  The only thing this issue probably needs is just to update the documentation to read 1.10.

**Comment by m13253** [comment]
The reason is one of the third-party libraries (miekg/dns) have been updated and only support Go 1.10 and later.

Please make sure you always try the latest version. (currently it's Go 1.11)

**Comment by mikedoug** [comment]
Yeah, I realized that it was due to a 3rd party library, but failed to mention that.  Thanks for updating the documentation for the next guy! :)
