### ISSUE TITLE
dnscrypt tag

### ISSUE THREAD

**Issue by jedisct1** [m13253/dns-over-https#3]
Hi,

And congrats for this great project making DNS-over-HTTPS more accessible.

Since this project is unrelated to DNSCrypt, and in order to avoid confusion, would it be possible to remove the "dnscrypt" label present in the Github description?

Thanks!

**Comment by m13253** [comment]
Sorry for confusion.
I have corrected the tags. Please check it.

**Comment by jedisct1** [comment]
Thanks a lot!
