### ISSUE TITLE
Could you tag 2.0.0?

### ISSUE THREAD

**Issue by Sherlock-Holo** [m13253/dns-over-https#35]
I see a commit about 

> Bump version 2.0.0

If you tag and release it, I will upgrade it on AUR

**Comment by m13253** [comment]
> If you tag and release it, I will upgrade it on AUR

I always modify the version number before releasing a new version, meaning that 2.0.0 is the next version and will be released in a few days.

I will release 2.0.0 after we made sure all load balancing algorithms works stably in production environment.

**Comment by m13253** [comment]
Tagged to 475894baaa3ccbc95ffdc8b8a7f592e75ac1ba7d
