### ISSUE TITLE
For Chinese 给中国开发者的建议

### ISSUE THREAD

**Issue by sky5454** [m13253/dns-over-https#49]
In China, golang.org has been ban. But we can do it as follow.
推荐没有梯子的中国开发者使用go代理服务器，如下
In Linux:
git clone --depth=1 https://github.com/m13253/dns-over-https.git
export GOPROXY=https://goproxy.io
make
....

In Arch/Manjaro:
export GOPROXY=https://goproxy.io
yay -S dns-over-https-client

And Windows like this, but I didn't have a try.

**Comment by m13253** [comment]
感谢你的帖子。

其实你可以设置 `http_proxy` 系列变量，方法如下：
```bash
export {http,https,ftp}_proxy=socks://127.0.0.1:1080
git clone --depth=1 https://github.com/m13253/dns-over-https.git
make
```

这个方法对大部分 Linux 命令行应用程序有效，但是不是所有应用程序都支持 SOCKS5 类型的代理服务器。

---

Thank you for your post.

You can also try to set `http_proxy` environment variables with the following method:
```bash
export {http,https,ftp}_proxy=socks://127.0.0.1:1080
git clone --depth=1 https://github.com/m13253/dns-over-https.git
make
```

This method is effective to most Linux command line programs, but not all programs support SOCKS5 proxy protocol.
