### ISSUE TITLE
Active: activating (auto-restart)

### ISSUE THREAD

**Issue by thb007** [m13253/dns-over-https#56]
```
root@iZwz9d1rjhrzzxa4lsoi93Z:~/build/dns-over-https-2.0.1# systemctl restart doh-server
root@iZwz9d1rjhrzzxa4lsoi93Z:~/build/dns-over-https-2.0.1# systemctl status doh-server
● doh-server.service - DNS-over-HTTPS Server
   Loaded: loaded (/usr/lib/systemd/system/doh-server.service; disabled; vendor preset: enabled)
   Active: activating (auto-restart) since Wed 2019-10-02 12:23:42 CST; 2s ago
     Docs: https://github.com/m13253/dns-over-https
  Process: 25954 ExecStart=/usr/local/bin/doh-server -conf /etc/dns-over-https/doh-server.conf (code=exited, status=0/SUC
 Main PID: 25954 (code=exited, status=0/SUCCESS)
lines 1-6/6 (END)

```

Unable to start the program, how can I solve it?

**Comment by m13253** [comment]
May I have a look at the output of
```
sudo journalctl -u doh-server
```

**Comment by thb007** [comment]
``https://github.com/m13253/dns-over-https/issues/56#issuecomment-537340149

**Comment by m13253** [comment]
It might be a problem at systemd side, would you please try to execute
```
sudo /usr/local/bin/doh-server -conf /etc/dns-over-https/doh-server.conf
```
by yourself, to distinguish whether it's a systemd problem or my problem?

**Comment by thb007** [comment]
The server is China Alibaba ECS

```
root@iZwz9d1rjhrzzxa4lsoi93Z:~/build/dns-over-https-2.0.1# sudo /usr/local/bin/doh-server -conf /etc/dns-over-https/doh-server.conf
2019/10/02 13:34:59 listen tcp [::1]:8053: bind: cannot assign requested address
```

**Comment by thb007** [comment]
> 这可能是系统方面的问题，请您尝试执行
> 
> ```
> sudo /usr/local/bin/doh-server -conf /etc/dns-over-https/doh-server.conf
> ```
> 
> 自己辨别是系统问题还是我的问题？

https://github.com/m13253/dns-over-https/issues/56#issuecomment-537342766

**Comment by m13253** [comment]
> The server is China Alibaba ECS

Alibaba has disabled IPv6 on the server. You may try one of the following solutions:

1. Enable IPv6.
   The configuration file my be located at `/etc/sysctl.conf` or `/etc/sysctl.d`. There you may find anything similar to `net.ipv6.conf.all.disable_ipv6 = 1`. Delete it.

2. Disable IPv6 and use IPv4 only.
   You will need to replace `[::1]` to `127.0.0.1` in `/etc/dns-over-https/doh-server.conf`.

阿里云默认关闭 IPv6。您可以尝试以下解决方法其中的一个：

1. 启用 IPv6。
   配置文件在 `/etc/sysctl.conf` 或者 `/etc/sysctl.d`。你应该能找到一行 `net.ipv6.conf.all.disable_ipv6 = 1`，删除它。

2. 禁用 IPv6，只使用 IPv4。
  这样的话请修改 `/etc/dns-over-https/doh-server.conf`，将 `[::1]` 替换成 `127.0.0.1`。

**Comment by thb007** [comment]
```
root@iZwz9d1rjhrzzxa4lsoi93Z:~/build/dns-over-https-2.0.1# systemctl status doh-server
● doh-server.service - DNS-over-HTTPS Server
   Loaded: loaded (/usr/lib/systemd/system/doh-server.service; disabled; vendor preset: enabled)
   Active: active (running) since Wed 2019-10-02 13:48:53 CST; 8s ago
     Docs: https://github.com/m13253/dns-over-https
 Main PID: 1458 (doh-server)
    Tasks: 5 (limit: 4915)
   CGroup: /system.slice/doh-server.service
           └─1458 /usr/local/bin/doh-server -conf /etc/dns-over-https/doh-server.conf

Oct 02 13:48:53 iZwz9d1rjhrzzxa4lsoi93Z systemd[1]: Stopped DNS-over-HTTPS Server.
Oct 02 13:48:53 iZwz9d1rjhrzzxa4lsoi93Z systemd[1]: Started DNS-over-HTTPS Server.
root@iZwz9d1rjhrzzxa4lsoi93Z:~/build/dns-over-https-2.0.1#
```
Thank you, already ok
