### ISSUE TITLE
Weird logs from doh-server

### ISSUE THREAD

**Issue by chew-z** [m13253/dns-over-https#59]
Hello,

Since latest release doh-server is making a lot of writings to syslog like below, despite verbose=false. Not very informative - at least for me. Can it be turned off?

Looks like [number stations](https://en.wikipedia.org/wiki/Numbers_station) to me ;-)

```
Oct 28 08:15:08 warrior doh-server[24450]: [0 4 3 4]
Oct 28 08:15:17 warrior doh-server[24450]: [0 4 3 4]
Oct 28 08:15:23 warrior doh-server[24450]: [0 4 3 4]
Oct 28 08:15:38 warrior doh-server[24450]: [0 4 3 4]
Oct 28 08:15:53 warrior doh-server[24450]: [0 4 3 4]
Oct 28 08:16:00 warrior doh-server[24450]: [0 4 3 4]
Oct 28 08:16:08 warrior doh-server[24450]: [0 4 3 4]
Oct 28 08:16:10 warrior doh-server[24450]: [0 4 3 4]
Oct 28 08:16:24 warrior doh-server[24450]: [0 4 3 4]
Oct 28 08:16:39 warrior doh-server[24450]: [0 4 3 4]
Oct 28 08:16:54 warrior doh-server[24450]: [0 4 3 4]
Oct 28 08:17:09 warrior doh-server[24450]: [0 4 3 4]
```

**Comment by m13253** [comment]
Thank you for your report!

I am currently investigating the problem. Please stay tuned.

**Comment by m13253** [comment]
Would you please test commit 82317bd63ebe6386303700ef71152b5aff2b09ed?
I guess the logs are coming from that line of code.

**Comment by chew-z** [comment]
It seems OK to me. Weird writes to syslog stoped now.

Thank you.

I really appreciate doh-server and doh-client...
