### ISSUE TITLE
Need conditional forwarders

### ISSUE THREAD

**Issue by djlucas** [m13253/dns-over-https#64]
For hybrid setups, an option for conditional forwarders would be appreciated. In this case, I am testing with a bind server listening on 127.0.0.1:54. In the interim, I've just used the bind server as the forwarder, with it's own forwarders in tact. While an acceptable workaround, this is probably overkill.

**Comment by djlucas** [comment]
Actually, on second thought, this configuration is fine. Don't complicate it. Along the same lines, however, while using 0.0.10.in-addr.arpa in passthrough domains works, this does not seem to be documented. I'd likely have been lost if I didn't know DNS fairly well as I almost didn't bother trying it. I'm actually going to close this, it's not really a bug, but please consider adding a commented example like above to the default client passthrough configuration as a helpful pointer.

**Comment by m13253** [comment]
Thank you for your message.

I haven't realized that the "passthrough" feature can be used for conditional forwarding. :-)
However this feature is too simple and does not support forwarding to multiple split domains, maybe it is still not mature to be documented I guess?
