### ISSUE TITLE
question: how to use random resolving?

### ISSUE THREAD

**Issue by monperrus** [m13253/dns-over-https#66]
Hi!

the code suggests that one can randomize the upstream servers:

```
Random   = "random"
NginxWRR = "weighted_round_robin"
LVSWRR   = "lvs_weighted_round_robin"
```

How to configure dns-over-https to use it?

**Comment by m13253** [comment]
In the `doh-client.conf`, find the following lines:
```toml
# available selector: random or weighted_round_robin or lvs_weighted_round_robin
upstream_selector = "random"
```
The default is already "random".

When you have more than one upstream servers, a random upstream server will be chosen for each request.

**Comment by monperrus** [comment]
thanks, see #67

**Comment by monperrus** [comment]
One problem with pure randomization is that  "over time (days, weeks) any resolver you use (either in round robin or with a random distribution) will likely acquire enough information about an end user to profile", which is a problem for privacy ([source](https://github.com/getdnsapi/stubby/issues/95#issuecomment-379708650))

One solution for that is a pseudo-random choice: "the choice of the server is consistent: if the same domain is resolved twice, the same DoH server for both queries is used". This is implemented for instance in [nss-tls](https://github.com/dimkr/nss-tls).

What about supporting `upstream_selector = "pseudo-random"`?

**Comment by m13253** [comment]
It's a good idea. And I suggest we name the selector "hostname_hash" or "hash" to match the naming of other load balancers.

I currently do not have time to implement new feature. So please help me if you are willing to. Pull requests are welcome. <3
