### ISSUE TITLE
Missing SysVinit Script

### ISSUE THREAD

**Issue by Ryushin** [m13253/dns-over-https#69]
There does not seem to be a SysVinit script included with the source.

**Comment by m13253** [comment]
Sorry, I personally have no preference on SysVinit.
But if you are a packager of a distribution, you may include SysVinit scripts in that package.

The main reason is the freedom of writing the script makes it basically possible to do anything besides starting and stopping a process. Also different distributions have different styles to write SysVinit scripts.

Therefore I prefer to rely on the distribution to provide SysVinit scripts. And I do not plan to provide any.
