### ISSUE TITLE
Add configure script

### ISSUE THREAD

**Issue by Ryushin** [m13253/dns-over-https#70]
Please add a configure script so prefix options can be added.  Such as prefix=/opt/dns-over-https and a server only install option so client pieces are not installed.

**Comment by m13253** [comment]
Thank you for your message.

I guess I already provided DESTDIR and PREFIX support in the Makefile. Why to add a `./configure` when the program do not need to configure anything?

And I personally don't think it is necessary to split into 2 packages -- The number of files are already very small. If we split them even smaller, we will have very tiny package fragments which seems to be unnecessary.

Anyhow, I will plan a rearrangement to the files in the repo so they will be neater.
