### ISSUE TITLE
configurable ECS addresses to defeat NAT / IPv6 tunnels inefficiency

### ISSUE THREAD

**Issue by lilydjwg** [m13253/dns-over-https#73]
I need to configure ECS addresses used for the following scenarios:

## NAT

Some ISPs will NAT to other ISP addresses (e.g. 长城宽带). So When I use 长城宽带, usually another outgoing address is used instead to access the DNS server (e.g. NATed to 中国联通 or 中国电信) but some CDNs do have nodes inside my ISP's network (长城宽带).

## IPv6 tunnels

I don't have IPv6 from my ISP but it's fun so I come up with a tunnel instead. When requesting DNS via this tunnel however, I receive A records optimized for my IPv6 tunnel.

BTW there seems to be a cache that ignores manually specified ECS addresses (via dig +subnet=xxx).

**Comment by m13253** [comment]
Thank you for your message. Now I understand what you mean.

> BTW there seems to be a cache that ignores manually specified ECS addresses (via dig +subnet=xxx).

There should not be a cache. Which upstream server do you use?

> I need to configure ECS addresses used for the following scenarios:

This feature is also requested in issue #32. I understand the situation in China where small ISPs use NATed transits to save money.
But I am afraid making ECS-spoofing feature too easy to use would do harm -- resulting DNS service providers to gradually distrust ECS records (actually there are already some servers doing so).

Therefore I have made [a separate program](https://github.com/m13253/geodns-injector) to perform this function. The program is specially designed for network environment in China. Would you like to check that out?

**Comment by lilydjwg** [comment]
> should not be a cache. Which upstream server do you use? The upstream server itself supports ECS but may have a cache that is unaware of ECS. This phenomenon is quite common when I tested several DNS server software.

Ahhh yes, it seems that the upstream caches them ignoring ECS and there are multiple servers. I'm using doh.dns.sb.

> Therefore I have made a separate program to perform this function. The program is specially designed for network environment in China. Would you like to check that out?

It would work. It turns out I'm already providing ECS records in my own DNS proxy....It failed my expectation only when I wanted to query DoH specifically (and it provided surprising results since when I don't have IPv6 the ECS records actually point to my private network so it doesn't have any effect).

**Comment by m13253** [comment]
Maybe solved with #92
