### ISSUE TITLE
Choose different upstream DNS by a domain list

### ISSUE THREAD

**Issue by wdhwg001** [m13253/dns-over-https#94]
Hi,

Thanks for creating such an amazing project!

I'm currently using it to establish a pollution-free DOH server as well as a proxy server together. I realised that for PRC domains, querying DNSPod with `X-Forwarded-For` that contains the client IP can get the best result. But for other domains, the best option is to query Google DNS with a specific IP (the IP of the proxy server) or omit the ECS entirely.

It would be really nice to have such a list filtering function.

**Comment by m13253** [comment]
Closing because I think this problem can be solved by other software.
Since I can't implement this feature as good as others, I want to leave the problem to those software.
