### ISSUE TITLE
Use of loopback address as upstream DNS server fails

### ISSUE THREAD

**Issue by satishweb** [m13253/dns-over-https#95]
Hi @m13253 ,

I have noticed that using loopback address as DNS upstream server does not work with current version of doh-server (2.2.4).

**DOH-Server Config:**
```
072e6a06e523:/server# cat doh-server.conf
listen = [ ":8053" ]
local_addr = ""
cert = ""
key = ""
path = "/getnsrecord"
upstream = [ "udp:127.0.0.1:53" ]
timeout = 10
tries = 3
verbose = true
log_guessed_client_ip = false
```

**Curl Test Logs:**
```
072e6a06e523:/# curl -I 'http://localhost:8053/getnsrecord?name=google.com&type=A'
HTTP/1.1 503 Service Unavailable
Access-Control-Allow-Headers: Content-Type
Access-Control-Allow-Methods: GET, HEAD, OPTIONS, POST
Access-Control-Allow-Origin: *
Access-Control-Max-Age: 3600
Content-Type: application/json; charset=UTF-8
Server: DNS-over-HTTPS/2.2.4 (+https://github.com/m13253/dns-over-https)
X-Powered-By: DNS-over-HTTPS/2.2.4 (+https://github.com/m13253/dns-over-https)
Date: Sat, 26 Dec 2020 05:41:50 GMT
Content-Length: 114
```

**DOH-Server console logs:**
```
072e6a06e523:/server#  /server/doh-server -conf /server/doh-server.conf
2020/12/26 05:41:50 DNS error from upstream udp:127.0.0.1:53: read udp 127.0.0.1:53131->127.0.0.1:53: read: connection refused
2020/12/26 05:41:50 DNS error from upstream udp:127.0.0.1:53: read udp 127.0.0.1:55126->127.0.0.1:53: read: connection refused
2020/12/26 05:41:50 DNS error from upstream udp:127.0.0.1:53: read udp 127.0.0.1:55747->127.0.0.1:53: read: connection refused
127.0.0.1 - - [26/Dec/2020:05:41:50 +0000] "HEAD /getnsrecord?name=google.com&type=A HTTP/1.1" 503 114 "" "curl/7.64.0"
```

**Simple nslookup test using loopback address was successful:**
```
072e6a06e523:/server# nslookup google.com 127.0.0.1
Server:    127.0.0.1
Address 1: 127.0.0.1 localhost

Name:      google.com
Address 1: 172.217.14.78
Address 2: 2607:f8b0:4005:807::200e
```

Please let me know if this is expected behavior or there is something that needs to be done to allow use of loopback address as upstream DNS server in DOH configuration. 

**Steps to reproduce**
1.  Run docker command to launch doh-server container
```
docker run -itd \
  --name doh-server \
  -e UPSTREAM_DNS_SERVER='udp:127.0.0.1:53' \
  -e DEBUG=1 \
  -e DOH_SERVER_VERBOSE=true \
  satishweb/doh-server \
sleep 36000
```
2. Start doh-server inside the container in console mode
```
docker exec -it doh-server /server/doh-server -conf /server/doh-server.conf
```
3. Add curl and execute curl test command
```
docker exec -it doh-server apk add curl
docker exec -it doh-server curl -I 'localhost:8053/getnsrecord?name=google.com&type=A'
```
4. To open shell: `docker exec -it doh-server bash`
5. Cleanup: `docker rm -f doh-server`

**Comment by satishweb** [comment]
This was discovered as part of testing done for issue: https://github.com/satishweb/docker-doh/issues/1

**Comment by m13253** [comment]
Thank you for the report.
This problem is very weird because I also use localhost upstream in my own deployment.

Have you tried this configuration outside Docker?

**Comment by satishweb** [comment]
It works without docker.
Need some help on debugging doh-server inside docker container to find the root cause. We need more logs than just `read udp 127.0.0.1:53131->127.0.0.1:53: read: connection refused`.

**Comment by m13253** [comment]
> It works without docker.

I believe there must be something wrong with the docker environment. I mean, I also run doh-server inside docker and it was fine.



>  Need some help on debugging doh-server inside docker container to find the root cause. We need more logs than just `read udp 127.0.0.1:53131->127.0.0.1:53: read: connection refused`.

I would like to provide any help if I can. However currently the only thing I know is that the `sendto` system call failed with `ECONNREFUSED`. This is probably because the Linux network stack received a packet of icmp-port-unreachable.
I suggest you check your `iptables` and/or `nftables` settings, use `ss -lunp` to obtain a list of UDP listeners, and try to obtain a packat capture with `tcpdump`.

**Comment by tycho** [comment]
I ran into this as well, without any docker involvement. The local DNS server is dnsmasq. My workaround is to use `tcp:127.0.0.1:53` as the only item in the `upstream` list, but that seems slightly heavy-handed so a real solution would be nice too.

I can try for a packet capture if that is the next step.

**Comment by m13253** [comment]
I tried your configuration and cannot reproduce.
It would be better if we can have a packet capture.

**Comment by satishweb** [comment]
@tycho Was this fixed for you or are you still with the workaround solution? I was not able to reproduce this issue on my system. It happens only inside the docker container for me.

**Comment by tycho** [comment]
I just built and tested the latest git revision and it seems to work at the moment, without the TCP workaround.

**Comment by satishweb** [comment]
Sounds good. I am going to mark this issue as resolved for now.
