### ISSUE TITLE
X-Real-IP for private address not respected if ecs_allow_non_global_ip=true

### ISSUE THREAD

**Issue by tycho** [m13253/dns-over-https#97]
I found that I had to set `ecs_allow_non_global_ip=false` in order for doh-server to respect the `X-Real-IP` header and send private addresses to upstream, which is the *opposite* of what that config variable is apparently intended to mean.

The problem seems to be that config file variable `ecs_allow_non_global_ip` is read to in-memory variable `LocalIPFilter` as-is, but the logical meaning of the two values is different. i.e. `LocalIPFilter=true` is treated as meaning "filter out local IPs", while `ecs_allow_non_global_ip=true` is supposed to mean "do NOT filter out local IPs".

**Comment by m13253** [comment]
Related issue #92 
@achauvinhameau

**Comment by m13253** [comment]
I believe @achauvinhameau can fix this problem, since this feature is introduced in PR #92.

**Comment by achauvinhameau** [comment]
fix proposed in commit c1fdf2a (07/01)

**Comment by m13253** [comment]
> fix proposed in commit [c1fdf2a](https://github.com/m13253/dns-over-https/commit/c1fdf2a7eef0b16ad638ae4824f03c438198cc14) (07/01)

Thank you! Will close this issue when that PR is merged.
